name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v337
      
    - name: Install wasm32-unknown-unknown target
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
      
    - name: Set up trunk
      uses: jetli/trunk-action@v0.4.0
      
    - name: Build
      run: "trunk build --release"
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
